# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Employee/employee.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Response import response_pb2 as Response_dot_response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Employee/employee.proto',
  package='employee',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x45mployee/employee.proto\x12\x08\x65mployee\x1a\x17Response/response.proto\"!\n\x0f\x45mployeeRequest\x12\x0e\n\x06\x65mp_id\x18\x01 \x01(\x03\"a\n\x08\x45mployee\x12\x0e\n\x06\x65mp_id\x18\x01 \x01(\x03\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x11\n\tjob_title\x18\x04 \x01(\t\x12\x0b\n\x03\x64ob\x18\x05 \x01(\t\"2\n\tEmployees\x12%\n\temployees\x18\x01 \x03(\x0b\x32\x12.employee.Employee\"\x07\n\x05\x45mpty\"^\n\x10\x45mployeeResponse\x12$\n\x08response\x18\x01 \x01(\x0b\x32\x12.employee.Response\x12$\n\x08\x65mployee\x18\x02 \x01(\x0b\x32\x12.employee.Employee2\x92\x01\n\x0f\x45mployeeService\x12\x46\n\x0bGetEmployee\x12\x19.employee.EmployeeRequest\x1a\x1a.employee.EmployeeResponse\"\x00\x12\x37\n\x0cGetEmployees\x12\x0f.employee.Empty\x1a\x12.employee.Employee\"\x00\x30\x01\x62\x06proto3'
  ,
  dependencies=[Response_dot_response__pb2.DESCRIPTOR,])




_EMPLOYEEREQUEST = _descriptor.Descriptor(
  name='EmployeeRequest',
  full_name='employee.EmployeeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='emp_id', full_name='employee.EmployeeRequest.emp_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=95,
)


_EMPLOYEE = _descriptor.Descriptor(
  name='Employee',
  full_name='employee.Employee',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='emp_id', full_name='employee.Employee.emp_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='first_name', full_name='employee.Employee.first_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='employee.Employee.last_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_title', full_name='employee.Employee.job_title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dob', full_name='employee.Employee.dob', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=194,
)


_EMPLOYEES = _descriptor.Descriptor(
  name='Employees',
  full_name='employee.Employees',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='employees', full_name='employee.Employees.employees', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=246,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='employee.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=255,
)


_EMPLOYEERESPONSE = _descriptor.Descriptor(
  name='EmployeeResponse',
  full_name='employee.EmployeeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='employee.EmployeeResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='employee', full_name='employee.EmployeeResponse.employee', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=351,
)

_EMPLOYEES.fields_by_name['employees'].message_type = _EMPLOYEE
_EMPLOYEERESPONSE.fields_by_name['response'].message_type = Response_dot_response__pb2._RESPONSE
_EMPLOYEERESPONSE.fields_by_name['employee'].message_type = _EMPLOYEE
DESCRIPTOR.message_types_by_name['EmployeeRequest'] = _EMPLOYEEREQUEST
DESCRIPTOR.message_types_by_name['Employee'] = _EMPLOYEE
DESCRIPTOR.message_types_by_name['Employees'] = _EMPLOYEES
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['EmployeeResponse'] = _EMPLOYEERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmployeeRequest = _reflection.GeneratedProtocolMessageType('EmployeeRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEEREQUEST,
  '__module__' : 'Employee.employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.EmployeeRequest)
  })
_sym_db.RegisterMessage(EmployeeRequest)

Employee = _reflection.GeneratedProtocolMessageType('Employee', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEE,
  '__module__' : 'Employee.employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.Employee)
  })
_sym_db.RegisterMessage(Employee)

Employees = _reflection.GeneratedProtocolMessageType('Employees', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEES,
  '__module__' : 'Employee.employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.Employees)
  })
_sym_db.RegisterMessage(Employees)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'Employee.employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.Empty)
  })
_sym_db.RegisterMessage(Empty)

EmployeeResponse = _reflection.GeneratedProtocolMessageType('EmployeeResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEERESPONSE,
  '__module__' : 'Employee.employee_pb2'
  # @@protoc_insertion_point(class_scope:employee.EmployeeResponse)
  })
_sym_db.RegisterMessage(EmployeeResponse)



_EMPLOYEESERVICE = _descriptor.ServiceDescriptor(
  name='EmployeeService',
  full_name='employee.EmployeeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=354,
  serialized_end=500,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetEmployee',
    full_name='employee.EmployeeService.GetEmployee',
    index=0,
    containing_service=None,
    input_type=_EMPLOYEEREQUEST,
    output_type=_EMPLOYEERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetEmployees',
    full_name='employee.EmployeeService.GetEmployees',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPLOYEE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMPLOYEESERVICE)

DESCRIPTOR.services_by_name['EmployeeService'] = _EMPLOYEESERVICE

# @@protoc_insertion_point(module_scope)
