# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Validation/validation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Validation/validation.proto',
  package='validation',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bValidation/validation.proto\x12\nvalidation\"#\n\x13ValidateNameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"%\n\x14ValidateNameResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x32h\n\x11ValidationService\x12S\n\x0cValidateName\x12\x1f.validation.ValidateNameRequest\x1a .validation.ValidateNameResponse\"\x00\x62\x06proto3'
)




_VALIDATENAMEREQUEST = _descriptor.Descriptor(
  name='ValidateNameRequest',
  full_name='validation.ValidateNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='validation.ValidateNameRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=78,
)


_VALIDATENAMERESPONSE = _descriptor.Descriptor(
  name='ValidateNameResponse',
  full_name='validation.ValidateNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid', full_name='validation.ValidateNameResponse.valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['ValidateNameRequest'] = _VALIDATENAMEREQUEST
DESCRIPTOR.message_types_by_name['ValidateNameResponse'] = _VALIDATENAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValidateNameRequest = _reflection.GeneratedProtocolMessageType('ValidateNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATENAMEREQUEST,
  '__module__' : 'Validation.validation_pb2'
  # @@protoc_insertion_point(class_scope:validation.ValidateNameRequest)
  })
_sym_db.RegisterMessage(ValidateNameRequest)

ValidateNameResponse = _reflection.GeneratedProtocolMessageType('ValidateNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _VALIDATENAMERESPONSE,
  '__module__' : 'Validation.validation_pb2'
  # @@protoc_insertion_point(class_scope:validation.ValidateNameResponse)
  })
_sym_db.RegisterMessage(ValidateNameResponse)



_VALIDATIONSERVICE = _descriptor.ServiceDescriptor(
  name='ValidationService',
  full_name='validation.ValidationService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=119,
  serialized_end=223,
  methods=[
  _descriptor.MethodDescriptor(
    name='ValidateName',
    full_name='validation.ValidationService.ValidateName',
    index=0,
    containing_service=None,
    input_type=_VALIDATENAMEREQUEST,
    output_type=_VALIDATENAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_VALIDATIONSERVICE)

DESCRIPTOR.services_by_name['ValidationService'] = _VALIDATIONSERVICE

# @@protoc_insertion_point(module_scope)
