# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from Validation import validation_pb2 as Validation_dot_validation__pb2


class ValidationServiceStub(object):
    """ValidationService represents service/method to
    validate name
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateName = channel.unary_unary(
                '/validation.ValidationService/ValidateName',
                request_serializer=Validation_dot_validation__pb2.ValidateNameRequest.SerializeToString,
                response_deserializer=Validation_dot_validation__pb2.ValidateNameResponse.FromString,
                )


class ValidationServiceServicer(object):
    """ValidationService represents service/method to
    validate name
    """

    def ValidateName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ValidationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateName': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateName,
                    request_deserializer=Validation_dot_validation__pb2.ValidateNameRequest.FromString,
                    response_serializer=Validation_dot_validation__pb2.ValidateNameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'validation.ValidationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ValidationService(object):
    """ValidationService represents service/method to
    validate name
    """

    @staticmethod
    def ValidateName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/validation.ValidationService/ValidateName',
            Validation_dot_validation__pb2.ValidateNameRequest.SerializeToString,
            Validation_dot_validation__pb2.ValidateNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
